// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-cu/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommitService creates a new instance of MockCommitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommitService {
	mock := &MockCommitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommitService is an autogenerated mock type for the CommitService type
type MockCommitService struct {
	mock.Mock
}

type MockCommitService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommitService) EXPECT() *MockCommitService_Expecter {
	return &MockCommitService_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockCommitService
func (_mock *MockCommitService) Commit(ctx context.Context, cuRepoPath string, message string) ([]types.DepChange, string, error) {
	ret := _mock.Called(ctx, cuRepoPath, message)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 []types.DepChange
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]types.DepChange, string, error)); ok {
		return returnFunc(ctx, cuRepoPath, message)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []types.DepChange); ok {
		r0 = returnFunc(ctx, cuRepoPath, message)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.DepChange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, cuRepoPath, message)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, cuRepoPath, message)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCommitService_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockCommitService_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoPath string
//   - message string
func (_e *MockCommitService_Expecter) Commit(ctx interface{}, cuRepoPath interface{}, message interface{}) *MockCommitService_Commit_Call {
	return &MockCommitService_Commit_Call{Call: _e.mock.On("Commit", ctx, cuRepoPath, message)}
}

func (_c *MockCommitService_Commit_Call) Run(run func(ctx context.Context, cuRepoPath string, message string)) *MockCommitService_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommitService_Commit_Call) Return(depChanges []types.DepChange, s string, err error) *MockCommitService_Commit_Call {
	_c.Call.Return(depChanges, s, err)
	return _c
}

func (_c *MockCommitService_Commit_Call) RunAndReturn(run func(ctx context.Context, cuRepoPath string, message string) ([]types.DepChange, string, error)) *MockCommitService_Commit_Call {
	_c.Call.Return(run)
	return _c
}
