// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-cu/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCompoService creates a new instance of MockCompoService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCompoService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCompoService {
	mock := &MockCompoService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCompoService is an autogenerated mock type for the CompoService type
type MockCompoService struct {
	mock.Mock
}

type MockCompoService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCompoService) EXPECT() *MockCompoService_Expecter {
	return &MockCompoService_Expecter{mock: &_m.Mock}
}

// Checkout provides a mock function for the type MockCompoService
func (_mock *MockCompoService) Checkout(ctx context.Context, cuRepoPath string, branch string) error {
	ret := _mock.Called(ctx, cuRepoPath, branch)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, cuRepoPath, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCompoService_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockCompoService_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoPath string
//   - branch string
func (_e *MockCompoService_Expecter) Checkout(ctx interface{}, cuRepoPath interface{}, branch interface{}) *MockCompoService_Checkout_Call {
	return &MockCompoService_Checkout_Call{Call: _e.mock.On("Checkout", ctx, cuRepoPath, branch)}
}

func (_c *MockCompoService_Checkout_Call) Run(run func(ctx context.Context, cuRepoPath string, branch string)) *MockCompoService_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCompoService_Checkout_Call) Return(err error) *MockCompoService_Checkout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCompoService_Checkout_Call) RunAndReturn(run func(ctx context.Context, cuRepoPath string, branch string) error) *MockCompoService_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentBranch provides a mock function for the type MockCompoService
func (_mock *MockCompoService) CurrentBranch(ctx context.Context, cuRepoPath string) (string, error) {
	ret := _mock.Called(ctx, cuRepoPath)

	if len(ret) == 0 {
		panic("no return value specified for CurrentBranch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, cuRepoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, cuRepoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cuRepoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompoService_CurrentBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentBranch'
type MockCompoService_CurrentBranch_Call struct {
	*mock.Call
}

// CurrentBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoPath string
func (_e *MockCompoService_Expecter) CurrentBranch(ctx interface{}, cuRepoPath interface{}) *MockCompoService_CurrentBranch_Call {
	return &MockCompoService_CurrentBranch_Call{Call: _e.mock.On("CurrentBranch", ctx, cuRepoPath)}
}

func (_c *MockCompoService_CurrentBranch_Call) Run(run func(ctx context.Context, cuRepoPath string)) *MockCompoService_CurrentBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompoService_CurrentBranch_Call) Return(s string, err error) *MockCompoService_CurrentBranch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCompoService_CurrentBranch_Call) RunAndReturn(run func(ctx context.Context, cuRepoPath string) (string, error)) *MockCompoService_CurrentBranch_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockCompoService
func (_mock *MockCompoService) Init(ctx context.Context, cuRepoURL string, cuRepoPath string, workspacePath string, branch string) (*types.Compo, error) {
	ret := _mock.Called(ctx, cuRepoURL, cuRepoPath, workspacePath, branch)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 *types.Compo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*types.Compo, error)); ok {
		return returnFunc(ctx, cuRepoURL, cuRepoPath, workspacePath, branch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *types.Compo); ok {
		r0 = returnFunc(ctx, cuRepoURL, cuRepoPath, workspacePath, branch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Compo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, cuRepoURL, cuRepoPath, workspacePath, branch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompoService_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockCompoService_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoURL string
//   - cuRepoPath string
//   - workspacePath string
//   - branch string
func (_e *MockCompoService_Expecter) Init(ctx interface{}, cuRepoURL interface{}, cuRepoPath interface{}, workspacePath interface{}, branch interface{}) *MockCompoService_Init_Call {
	return &MockCompoService_Init_Call{Call: _e.mock.On("Init", ctx, cuRepoURL, cuRepoPath, workspacePath, branch)}
}

func (_c *MockCompoService_Init_Call) Run(run func(ctx context.Context, cuRepoURL string, cuRepoPath string, workspacePath string, branch string)) *MockCompoService_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCompoService_Init_Call) Return(compo *types.Compo, err error) *MockCompoService_Init_Call {
	_c.Call.Return(compo, err)
	return _c
}

func (_c *MockCompoService_Init_Call) RunAndReturn(run func(ctx context.Context, cuRepoURL string, cuRepoPath string, workspacePath string, branch string) (*types.Compo, error)) *MockCompoService_Init_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranches provides a mock function for the type MockCompoService
func (_mock *MockCompoService) ListBranches(ctx context.Context, cuRepoPath string) ([]string, error) {
	ret := _mock.Called(ctx, cuRepoPath)

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, cuRepoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, cuRepoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cuRepoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompoService_ListBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranches'
type MockCompoService_ListBranches_Call struct {
	*mock.Call
}

// ListBranches is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoPath string
func (_e *MockCompoService_Expecter) ListBranches(ctx interface{}, cuRepoPath interface{}) *MockCompoService_ListBranches_Call {
	return &MockCompoService_ListBranches_Call{Call: _e.mock.On("ListBranches", ctx, cuRepoPath)}
}

func (_c *MockCompoService_ListBranches_Call) Run(run func(ctx context.Context, cuRepoPath string)) *MockCompoService_ListBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompoService_ListBranches_Call) Return(strings []string, err error) *MockCompoService_ListBranches_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockCompoService_ListBranches_Call) RunAndReturn(run func(ctx context.Context, cuRepoPath string) ([]string, error)) *MockCompoService_ListBranches_Call {
	_c.Call.Return(run)
	return _c
}

// LoadCompo provides a mock function for the type MockCompoService
func (_mock *MockCompoService) LoadCompo(ctx context.Context, cuRepoPath string) (*types.Compo, error) {
	ret := _mock.Called(ctx, cuRepoPath)

	if len(ret) == 0 {
		panic("no return value specified for LoadCompo")
	}

	var r0 *types.Compo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*types.Compo, error)); ok {
		return returnFunc(ctx, cuRepoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *types.Compo); ok {
		r0 = returnFunc(ctx, cuRepoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Compo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cuRepoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompoService_LoadCompo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadCompo'
type MockCompoService_LoadCompo_Call struct {
	*mock.Call
}

// LoadCompo is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoPath string
func (_e *MockCompoService_Expecter) LoadCompo(ctx interface{}, cuRepoPath interface{}) *MockCompoService_LoadCompo_Call {
	return &MockCompoService_LoadCompo_Call{Call: _e.mock.On("LoadCompo", ctx, cuRepoPath)}
}

func (_c *MockCompoService_LoadCompo_Call) Run(run func(ctx context.Context, cuRepoPath string)) *MockCompoService_LoadCompo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompoService_LoadCompo_Call) Return(compo *types.Compo, err error) *MockCompoService_LoadCompo_Call {
	_c.Call.Return(compo, err)
	return _c
}

func (_c *MockCompoService_LoadCompo_Call) RunAndReturn(run func(ctx context.Context, cuRepoPath string) (*types.Compo, error)) *MockCompoService_LoadCompo_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockCompoService
func (_mock *MockCompoService) Status(ctx context.Context, cuRepoPath string) ([]types.DepChange, error) {
	ret := _mock.Called(ctx, cuRepoPath)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 []types.DepChange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]types.DepChange, error)); ok {
		return returnFunc(ctx, cuRepoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []types.DepChange); ok {
		r0 = returnFunc(ctx, cuRepoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.DepChange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, cuRepoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCompoService_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockCompoService_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoPath string
func (_e *MockCompoService_Expecter) Status(ctx interface{}, cuRepoPath interface{}) *MockCompoService_Status_Call {
	return &MockCompoService_Status_Call{Call: _e.mock.On("Status", ctx, cuRepoPath)}
}

func (_c *MockCompoService_Status_Call) Run(run func(ctx context.Context, cuRepoPath string)) *MockCompoService_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCompoService_Status_Call) Return(depChanges []types.DepChange, err error) *MockCompoService_Status_Call {
	_c.Call.Return(depChanges, err)
	return _c
}

func (_c *MockCompoService_Status_Call) RunAndReturn(run func(ctx context.Context, cuRepoPath string) ([]types.DepChange, error)) *MockCompoService_Status_Call {
	_c.Call.Return(run)
	return _c
}
