// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-cu/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSymlinkAdapter creates a new instance of MockSymlinkAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSymlinkAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSymlinkAdapter {
	mock := &MockSymlinkAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSymlinkAdapter is an autogenerated mock type for the SymlinkAdapter type
type MockSymlinkAdapter struct {
	mock.Mock
}

type MockSymlinkAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSymlinkAdapter) EXPECT() *MockSymlinkAdapter_Expecter {
	return &MockSymlinkAdapter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSymlinkAdapter
func (_mock *MockSymlinkAdapter) Create(ctx context.Context, cuRepoPath string, workspacePath string, compo types.Compo) error {
	ret := _mock.Called(ctx, cuRepoPath, workspacePath, compo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, types.Compo) error); ok {
		r0 = returnFunc(ctx, cuRepoPath, workspacePath, compo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSymlinkAdapter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSymlinkAdapter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cuRepoPath string
//   - workspacePath string
//   - compo types.Compo
func (_e *MockSymlinkAdapter_Expecter) Create(ctx interface{}, cuRepoPath interface{}, workspacePath interface{}, compo interface{}) *MockSymlinkAdapter_Create_Call {
	return &MockSymlinkAdapter_Create_Call{Call: _e.mock.On("Create", ctx, cuRepoPath, workspacePath, compo)}
}

func (_c *MockSymlinkAdapter_Create_Call) Run(run func(ctx context.Context, cuRepoPath string, workspacePath string, compo types.Compo)) *MockSymlinkAdapter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 types.Compo
		if args[3] != nil {
			arg3 = args[3].(types.Compo)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSymlinkAdapter_Create_Call) Return(err error) *MockSymlinkAdapter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSymlinkAdapter_Create_Call) RunAndReturn(run func(ctx context.Context, cuRepoPath string, workspacePath string, compo types.Compo) error) *MockSymlinkAdapter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockSymlinkAdapter
func (_mock *MockSymlinkAdapter) Remove(ctx context.Context, workspacePath string, compo types.Compo) error {
	ret := _mock.Called(ctx, workspacePath, compo)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Compo) error); ok {
		r0 = returnFunc(ctx, workspacePath, compo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSymlinkAdapter_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockSymlinkAdapter_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - workspacePath string
//   - compo types.Compo
func (_e *MockSymlinkAdapter_Expecter) Remove(ctx interface{}, workspacePath interface{}, compo interface{}) *MockSymlinkAdapter_Remove_Call {
	return &MockSymlinkAdapter_Remove_Call{Call: _e.mock.On("Remove", ctx, workspacePath, compo)}
}

func (_c *MockSymlinkAdapter_Remove_Call) Run(run func(ctx context.Context, workspacePath string, compo types.Compo)) *MockSymlinkAdapter_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Compo
		if args[2] != nil {
			arg2 = args[2].(types.Compo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSymlinkAdapter_Remove_Call) Return(err error) *MockSymlinkAdapter_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSymlinkAdapter_Remove_Call) RunAndReturn(run func(ctx context.Context, workspacePath string, compo types.Compo) error) *MockSymlinkAdapter_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockSymlinkAdapter
func (_mock *MockSymlinkAdapter) Verify(ctx context.Context, workspacePath string, compo types.Compo) (bool, error) {
	ret := _mock.Called(ctx, workspacePath, compo)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Compo) (bool, error)); ok {
		return returnFunc(ctx, workspacePath, compo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Compo) bool); ok {
		r0 = returnFunc(ctx, workspacePath, compo)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Compo) error); ok {
		r1 = returnFunc(ctx, workspacePath, compo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSymlinkAdapter_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockSymlinkAdapter_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - workspacePath string
//   - compo types.Compo
func (_e *MockSymlinkAdapter_Expecter) Verify(ctx interface{}, workspacePath interface{}, compo interface{}) *MockSymlinkAdapter_Verify_Call {
	return &MockSymlinkAdapter_Verify_Call{Call: _e.mock.On("Verify", ctx, workspacePath, compo)}
}

func (_c *MockSymlinkAdapter_Verify_Call) Run(run func(ctx context.Context, workspacePath string, compo types.Compo)) *MockSymlinkAdapter_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Compo
		if args[2] != nil {
			arg2 = args[2].(types.Compo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSymlinkAdapter_Verify_Call) Return(b bool, err error) *MockSymlinkAdapter_Verify_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSymlinkAdapter_Verify_Call) RunAndReturn(run func(ctx context.Context, workspacePath string, compo types.Compo) (bool, error)) *MockSymlinkAdapter_Verify_Call {
	_c.Call.Return(run)
	return _c
}
