// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-cu/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGitAdapter creates a new instance of MockGitAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitAdapter {
	mock := &MockGitAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGitAdapter is an autogenerated mock type for the GitAdapter type
type MockGitAdapter struct {
	mock.Mock
}

type MockGitAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitAdapter) EXPECT() *MockGitAdapter_Expecter {
	return &MockGitAdapter_Expecter{mock: &_m.Mock}
}

// Checkout provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) Checkout(ctx context.Context, repoPath string, branch string) error {
	ret := _mock.Called(ctx, repoPath, branch)

	if len(ret) == 0 {
		panic("no return value specified for Checkout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_Checkout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkout'
type MockGitAdapter_Checkout_Call struct {
	*mock.Call
}

// Checkout is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - branch string
func (_e *MockGitAdapter_Expecter) Checkout(ctx interface{}, repoPath interface{}, branch interface{}) *MockGitAdapter_Checkout_Call {
	return &MockGitAdapter_Checkout_Call{Call: _e.mock.On("Checkout", ctx, repoPath, branch)}
}

func (_c *MockGitAdapter_Checkout_Call) Run(run func(ctx context.Context, repoPath string, branch string)) *MockGitAdapter_Checkout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitAdapter_Checkout_Call) Return(err error) *MockGitAdapter_Checkout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_Checkout_Call) RunAndReturn(run func(ctx context.Context, repoPath string, branch string) error) *MockGitAdapter_Checkout_Call {
	_c.Call.Return(run)
	return _c
}

// Clone provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) Clone(ctx context.Context, url string, dest string) error {
	ret := _mock.Called(ctx, url, dest)

	if len(ret) == 0 {
		panic("no return value specified for Clone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, url, dest)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_Clone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clone'
type MockGitAdapter_Clone_Call struct {
	*mock.Call
}

// Clone is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - dest string
func (_e *MockGitAdapter_Expecter) Clone(ctx interface{}, url interface{}, dest interface{}) *MockGitAdapter_Clone_Call {
	return &MockGitAdapter_Clone_Call{Call: _e.mock.On("Clone", ctx, url, dest)}
}

func (_c *MockGitAdapter_Clone_Call) Run(run func(ctx context.Context, url string, dest string)) *MockGitAdapter_Clone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitAdapter_Clone_Call) Return(err error) *MockGitAdapter_Clone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_Clone_Call) RunAndReturn(run func(ctx context.Context, url string, dest string) error) *MockGitAdapter_Clone_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) Commit(ctx context.Context, repoPath string, message string) error {
	ret := _mock.Called(ctx, repoPath, message)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, repoPath, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockGitAdapter_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
//   - message string
func (_e *MockGitAdapter_Expecter) Commit(ctx interface{}, repoPath interface{}, message interface{}) *MockGitAdapter_Commit_Call {
	return &MockGitAdapter_Commit_Call{Call: _e.mock.On("Commit", ctx, repoPath, message)}
}

func (_c *MockGitAdapter_Commit_Call) Run(run func(ctx context.Context, repoPath string, message string)) *MockGitAdapter_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGitAdapter_Commit_Call) Return(err error) *MockGitAdapter_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_Commit_Call) RunAndReturn(run func(ctx context.Context, repoPath string, message string) error) *MockGitAdapter_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentBranch provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) CurrentBranch(ctx context.Context, repoPath string) (string, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for CurrentBranch")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitAdapter_CurrentBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentBranch'
type MockGitAdapter_CurrentBranch_Call struct {
	*mock.Call
}

// CurrentBranch is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) CurrentBranch(ctx interface{}, repoPath interface{}) *MockGitAdapter_CurrentBranch_Call {
	return &MockGitAdapter_CurrentBranch_Call{Call: _e.mock.On("CurrentBranch", ctx, repoPath)}
}

func (_c *MockGitAdapter_CurrentBranch_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_CurrentBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_CurrentBranch_Call) Return(s string, err error) *MockGitAdapter_CurrentBranch_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitAdapter_CurrentBranch_Call) RunAndReturn(run func(ctx context.Context, repoPath string) (string, error)) *MockGitAdapter_CurrentBranch_Call {
	_c.Call.Return(run)
	return _c
}

// CurrentCommitHash provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) CurrentCommitHash(ctx context.Context, repoPath string) (string, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for CurrentCommitHash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitAdapter_CurrentCommitHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CurrentCommitHash'
type MockGitAdapter_CurrentCommitHash_Call struct {
	*mock.Call
}

// CurrentCommitHash is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) CurrentCommitHash(ctx interface{}, repoPath interface{}) *MockGitAdapter_CurrentCommitHash_Call {
	return &MockGitAdapter_CurrentCommitHash_Call{Call: _e.mock.On("CurrentCommitHash", ctx, repoPath)}
}

func (_c *MockGitAdapter_CurrentCommitHash_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_CurrentCommitHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_CurrentCommitHash_Call) Return(s string, err error) *MockGitAdapter_CurrentCommitHash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitAdapter_CurrentCommitHash_Call) RunAndReturn(run func(ctx context.Context, repoPath string) (string, error)) *MockGitAdapter_CurrentCommitHash_Call {
	_c.Call.Return(run)
	return _c
}

// Diff provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) Diff(ctx context.Context, repoPath string) (string, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for Diff")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitAdapter_Diff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Diff'
type MockGitAdapter_Diff_Call struct {
	*mock.Call
}

// Diff is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) Diff(ctx interface{}, repoPath interface{}) *MockGitAdapter_Diff_Call {
	return &MockGitAdapter_Diff_Call{Call: _e.mock.On("Diff", ctx, repoPath)}
}

func (_c *MockGitAdapter_Diff_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_Diff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_Diff_Call) Return(s string, err error) *MockGitAdapter_Diff_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGitAdapter_Diff_Call) RunAndReturn(run func(ctx context.Context, repoPath string) (string, error)) *MockGitAdapter_Diff_Call {
	_c.Call.Return(run)
	return _c
}

// ListBranches provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) ListBranches(ctx context.Context, repoPath string) ([]string, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for ListBranches")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitAdapter_ListBranches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBranches'
type MockGitAdapter_ListBranches_Call struct {
	*mock.Call
}

// ListBranches is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) ListBranches(ctx interface{}, repoPath interface{}) *MockGitAdapter_ListBranches_Call {
	return &MockGitAdapter_ListBranches_Call{Call: _e.mock.On("ListBranches", ctx, repoPath)}
}

func (_c *MockGitAdapter_ListBranches_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_ListBranches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_ListBranches_Call) Return(strings []string, err error) *MockGitAdapter_ListBranches_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGitAdapter_ListBranches_Call) RunAndReturn(run func(ctx context.Context, repoPath string) ([]string, error)) *MockGitAdapter_ListBranches_Call {
	_c.Call.Return(run)
	return _c
}

// Pull provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) Pull(ctx context.Context, repoPath string) error {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for Pull")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockGitAdapter_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) Pull(ctx interface{}, repoPath interface{}) *MockGitAdapter_Pull_Call {
	return &MockGitAdapter_Pull_Call{Call: _e.mock.On("Pull", ctx, repoPath)}
}

func (_c *MockGitAdapter_Pull_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_Pull_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_Pull_Call) Return(err error) *MockGitAdapter_Pull_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_Pull_Call) RunAndReturn(run func(ctx context.Context, repoPath string) error) *MockGitAdapter_Pull_Call {
	_c.Call.Return(run)
	return _c
}

// Push provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) Push(ctx context.Context, repoPath string) error {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for Push")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGitAdapter_Push_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Push'
type MockGitAdapter_Push_Call struct {
	*mock.Call
}

// Push is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) Push(ctx interface{}, repoPath interface{}) *MockGitAdapter_Push_Call {
	return &MockGitAdapter_Push_Call{Call: _e.mock.On("Push", ctx, repoPath)}
}

func (_c *MockGitAdapter_Push_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_Push_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_Push_Call) Return(err error) *MockGitAdapter_Push_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGitAdapter_Push_Call) RunAndReturn(run func(ctx context.Context, repoPath string) error) *MockGitAdapter_Push_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockGitAdapter
func (_mock *MockGitAdapter) Status(ctx context.Context, repoPath string) ([]types.DepChange, error) {
	ret := _mock.Called(ctx, repoPath)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 []types.DepChange
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]types.DepChange, error)); ok {
		return returnFunc(ctx, repoPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []types.DepChange); ok {
		r0 = returnFunc(ctx, repoPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.DepChange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, repoPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGitAdapter_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockGitAdapter_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
//   - ctx context.Context
//   - repoPath string
func (_e *MockGitAdapter_Expecter) Status(ctx interface{}, repoPath interface{}) *MockGitAdapter_Status_Call {
	return &MockGitAdapter_Status_Call{Call: _e.mock.On("Status", ctx, repoPath)}
}

func (_c *MockGitAdapter_Status_Call) Run(run func(ctx context.Context, repoPath string)) *MockGitAdapter_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGitAdapter_Status_Call) Return(depChanges []types.DepChange, err error) *MockGitAdapter_Status_Call {
	_c.Call.Return(depChanges, err)
	return _c
}

func (_c *MockGitAdapter_Status_Call) RunAndReturn(run func(ctx context.Context, repoPath string) ([]types.DepChange, error)) *MockGitAdapter_Status_Call {
	_c.Call.Return(run)
	return _c
}
