// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockengine

import (
	"context"

	"github.com/alexandremahdhaoui/forge-cu/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGoCUEngine creates a new instance of MockGoCUEngine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoCUEngine(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoCUEngine {
	mock := &MockGoCUEngine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoCUEngine is an autogenerated mock type for the GoCUEngine type
type MockGoCUEngine struct {
	mock.Mock
}

type MockGoCUEngine_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoCUEngine) EXPECT() *MockGoCUEngine_Expecter {
	return &MockGoCUEngine_Expecter{mock: &_m.Mock}
}

// GoGet provides a mock function for the type MockGoCUEngine
func (_mock *MockGoCUEngine) GoGet(ctx context.Context, repoDir string, cuRepoPath string, pkg string, version string) ([]types.DepChange, string, error) {
	ret := _mock.Called(ctx, repoDir, cuRepoPath, pkg, version)

	if len(ret) == 0 {
		panic("no return value specified for GoGet")
	}

	var r0 []types.DepChange
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]types.DepChange, string, error)); ok {
		return returnFunc(ctx, repoDir, cuRepoPath, pkg, version)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) []types.DepChange); ok {
		r0 = returnFunc(ctx, repoDir, cuRepoPath, pkg, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.DepChange)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) string); ok {
		r1 = returnFunc(ctx, repoDir, cuRepoPath, pkg, version)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string) error); ok {
		r2 = returnFunc(ctx, repoDir, cuRepoPath, pkg, version)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockGoCUEngine_GoGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GoGet'
type MockGoCUEngine_GoGet_Call struct {
	*mock.Call
}

// GoGet is a helper method to define mock.On call
//   - ctx context.Context
//   - repoDir string
//   - cuRepoPath string
//   - pkg string
//   - version string
func (_e *MockGoCUEngine_Expecter) GoGet(ctx interface{}, repoDir interface{}, cuRepoPath interface{}, pkg interface{}, version interface{}) *MockGoCUEngine_GoGet_Call {
	return &MockGoCUEngine_GoGet_Call{Call: _e.mock.On("GoGet", ctx, repoDir, cuRepoPath, pkg, version)}
}

func (_c *MockGoCUEngine_GoGet_Call) Run(run func(ctx context.Context, repoDir string, cuRepoPath string, pkg string, version string)) *MockGoCUEngine_GoGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGoCUEngine_GoGet_Call) Return(depChanges []types.DepChange, s string, err error) *MockGoCUEngine_GoGet_Call {
	_c.Call.Return(depChanges, s, err)
	return _c
}

func (_c *MockGoCUEngine_GoGet_Call) RunAndReturn(run func(ctx context.Context, repoDir string, cuRepoPath string, pkg string, version string) ([]types.DepChange, string, error)) *MockGoCUEngine_GoGet_Call {
	_c.Call.Return(run)
	return _c
}
